export const LOADER = 'LOADER'

export const CLEAR_DATA = "CLEAR_DATA";

export const SET_FCM_TOKEN_SUCCESS = "SET_FCM_TOKEN_SUCCESS"
export const SET_FCM_TOKEN_FAILURE = "SET_FCM_TOKEN_FAILURE"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SIGNUP = "SIGNUP"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"

export const SAVE_USERINFO = "SAVE_USERINFO"
export const SAVE_USERINFO_FAILURE = "SAVE_USERINFO_FAILURE"
export const SAVE_USERINFO_SUCCESS = "SAVE_USERINFO_SUCCESS"

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"

export const TERMS_AND_CONDITIONS_SUCCESS = "TERMS_AND_CONDITIONS_SUCCESS"
export const TERMS_AND_CONDITIONS_FAILURE = "TERMS_AND_CONDITIONS_FAILURE"
export const TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"

export const PRIVACY_POLICY_SUCCESS = "PRIVACY_POLICY_SUCCESS"
export const PRIVACY_POLICY_FAILURE = "PRIVACY_POLICY_FAILURE"
export const PRIVACY_POLICY = "PRIVACY_POLICY"





